### ISSUE TITLE
Does not build with nix

### ISSUE THREAD

**Issue by ebzzry** [balsoft/lambda-launcher#9]
I tried to build it with

    nix build

However, I got the following:

    error: anonymous function at /nix/store/baz6w5n9v0b6l3lrlpz4976g9b9kd2q1-nixos-18.09.2498.22a606e20d6/nixos/pkgs/development/haskell-modules/generic-builder.nix:12:1 called with unexpected argument 'haddockFlags', at /nix/store/baz6w5n9v0b6l3lrlpz4976g9b9kd2q1-nixos-18.09.2498.22a606e20d6/nixos/lib/customisation.nix:69:12

**Comment by balsoft** [comment]
Yes, makes sense. This argument was added in unstable and wasn't backported to 18.09. It's not required for building.

**Comment by balsoft** [comment]
Should work now.

**Comment by ebzzry** [comment]
I have the following now:

```
these derivations will be built:
  /nix/store/dqsly1xgmvsnpm70h2f2d8k5js9gsj3n-remove-references-to.drv
  /nix/store/ah8fhx3c8jgv994vgs9x458l67nnz814-lambda-launcher-0.1.0.0.drv
these paths will be fetched (81.44 MiB download, 1531.98 MiB unpacked):
  /nix/store/0jdrni7gmj9cwivybjvlfq9w9h9iv4b0-xml-conduit-1.8.0-doc
  /nix/store/13nbs1kx82jp8xfz7snlpfdl68gpfd1i-haskell-gi-base-0.21.1-doc
  /nix/store/1w7nivvrd52cngyqaknvzdswn99raxk6-xml-conduit-1.8.0
  /nix/store/2cayak6265m6wiqpvzn74r3jk2bnw7fr-entropy-0.4.1.1-doc
  /nix/store/6hkwxjcrglkmqx1yvh80bi5gnxwk1s3d-gi-gtk-declarative-0.1.0
  /nix/store/6q9ylml1ak9k3k847zvlmwrhx59xk0hg-gi-glib-2.0.17
  /nix/store/81acvq5zliil9dd9c9h006w8snxqya5k-haskell-gi-overloading-1.0
  /nix/store/8bzx2i2nqqrj79zr6ab26x0am1b6r8db-SHA-1.6.4.4
  /nix/store/8wi4av7vvksddl4l68rmxrna3abzwnbf-crypto-api-0.13.3
  /nix/store/91a4dz8ggn1sh56wksllnk4hlkrgq2wh-gi-gtk-declarative-app-simple-0.1.0
  /nix/store/9hymbmh84dv0hk4c6ihsnly032kd353h-req-1.1.0-data
  /nix/store/aa148lwnm6ppiy27k7a133fwlphj93id-pipes-4.3.9-doc
  /nix/store/dly7cpk6z3a4khbwp0la6fbm78bs85la-gi-gdkpixbuf-2.0.16
  /nix/store/dvmlqbhb7hdb0w4fz8zszzzmcgad6zpr-haskell-gi-0.21.4-doc
  /nix/store/f3c5a26ng4j01ipqi3qpvfz8qh5r56kb-crypto-pubkey-types-0.4.3-doc
  /nix/store/frrxxlkxmg0yhgabrqcmlv6x9cmv1b10-regex-tdfa-1.2.3.1
  /nix/store/gm1ggslr73bf7fn8fa0mnyrvcs5zd1za-gi-gtk-3.0.24
  /nix/store/h75gnbnb5a7w9v1nv3di57n7x86hs4m0-haskell-lexer-1.0.1-doc
  /nix/store/haiyqfk7x0ac4j19am317h5xw6335r0a-mmorph-1.1.2-doc
  /nix/store/hhj80ngjb1pr1nw2wxxyhxay9s6nw524-RSA-2.3.0-doc
  /nix/store/i4ddykjf873vsg4f6l17gxjklnghbnqn-gobject-introspection-1.56.0-dev
  /nix/store/i77ck41jr4b86jsavrldzyh124br95gs-pipes-concurrency-2.0.11-doc
  /nix/store/ihhrw82d4pgyzs3griq5l3srlr2b0k7a-xdg-basedir-0.2.2
  /nix/store/jyps9mph07i82m2xkibk5fsi9r37dqxn-gi-gio-2.0.18
  /nix/store/kcrcigylc73plzahdi3nkbq4angs853x-crypto-pubkey-types-0.4.3
  /nix/store/kf9l6krhjfbq72qpb0rjpjqa32ggbrrc-haskell-lexer-1.0.1
  /nix/store/lfd4anlks1m9pwc3361455cfh1nnrr7s-gi-gdk-3.0.16
  /nix/store/lk77zg27gl3bfcd24ssn28fllld7pi6d-req-1.1.0-doc
  /nix/store/mfg915nin5k25dmzld67csr1xpwyyp2c-xml-types-0.3.6-doc
  /nix/store/ml5skdqp9qz1208msiyvjp77l5ks1l45-pipes-4.3.9
  /nix/store/mwmps0fp28nd4q5jpizc1a44q6xxkck0-haskell-gi-0.21.4
  /nix/store/nnm9jvqmkpf6x1cm220rpgcs28g78kry-SHA-1.6.4.4-doc
  /nix/store/p0cs5r4srpnvl0mhkslv4m0zhpm3fdbz-gi-gtk-declarative-0.1.0-doc
  /nix/store/p42g0sbdzbj1v08fpbbyb4wzdms4ln5z-RSA-2.3.0
  /nix/store/qqj71wcfxb58nrrns2k21l24w24i715d-authenticate-oauth-1.6
  /nix/store/qyvissiliwmp898f8z63dxh17s3l8j1m-pretty-show-1.7
  /nix/store/r0w21ddqr18cp1m84w30jm41xvyvlywh-regex-tdfa-1.2.3.1-doc
  /nix/store/r9ql25y0x7ycqwy2qjn2kidz5hxqpcsl-crypto-api-0.13.3-doc
  /nix/store/rszqpxm0ypb5yfcsbcm93zkin1sykhdr-gi-atk-2.0.15
  /nix/store/rz0562w0mk2qy628jp5gija2c9hp3irn-xdg-basedir-0.2.2-doc
  /nix/store/rzawymr61r7v91hwy2xdsg406qhrprzk-gi-gtk-declarative-app-simple-0.1.0-doc
  /nix/store/sfc24mw30slz81jmzn5r3xgpxyi153qf-gi-cairo-1.0.17
  /nix/store/vppwczww9s8hdjpn5nqcqgywszmv8p4a-pretty-show-1.7-data
  /nix/store/wb2vrb9aak8975cm5sar971fljyxx6xa-gi-pango-1.0.16
  /nix/store/wqx2n8ccgz2a604y267yqxl67g0fv1np-entropy-0.4.1.1
  /nix/store/x2xgjwy4ad2q6mic0zwzyi98ibpf02x1-pipes-concurrency-2.0.11
  /nix/store/xxsyfwcaqkxc08z2b4vbyrv2n2hmvwj3-gi-gobject-2.0.16
  /nix/store/xywlf842zcdav8hibn24pkk6lbfmqsy0-xml-types-0.3.6
  /nix/store/ycd5v40ybak5b2vl5qpb58csm81rrkmj-pretty-show-1.7-doc
  /nix/store/z8z81zpydvvjbk8pfwyaj58h8lg7csa4-haskell-gi-base-0.21.1
  /nix/store/zxmvdbf06jmr12abkihf4j55wx4j2s2g-req-1.1.0
  /nix/store/zz1v3vbdyw7jbchpldd11f7igycj9pqx-mmorph-1.1.2
  /nix/store/zzw0jmsl9y9ra6mw8lp5zz91wvlaalky-authenticate-oauth-1.6-doc
copying path '/nix/store/9hymbmh84dv0hk4c6ihsnly032kd353h-req-1.1.0-data' from 'https://cache.nixos.org'...
building '/nix/store/dqsly1xgmvsnpm70h2f2d8k5js9gsj3n-remove-references-to.drv'...
copying path '/nix/store/vppwczww9s8hdjpn5nqcqgywszmv8p4a-pretty-show-1.7-data' from 'https://cache.nixos.org'...
copying path '/nix/store/nnm9jvqmkpf6x1cm220rpgcs28g78kry-SHA-1.6.4.4-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/f3c5a26ng4j01ipqi3qpvfz8qh5r56kb-crypto-pubkey-types-0.4.3-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/2cayak6265m6wiqpvzn74r3jk2bnw7fr-entropy-0.4.1.1-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/i4ddykjf873vsg4f6l17gxjklnghbnqn-gobject-introspection-1.56.0-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/8bzx2i2nqqrj79zr6ab26x0am1b6r8db-SHA-1.6.4.4' from 'https://cache.nixos.org'...
copying path '/nix/store/r9ql25y0x7ycqwy2qjn2kidz5hxqpcsl-crypto-api-0.13.3-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/wqx2n8ccgz2a604y267yqxl67g0fv1np-entropy-0.4.1.1' from 'https://cache.nixos.org'...
copying path '/nix/store/13nbs1kx82jp8xfz7snlpfdl68gpfd1i-haskell-gi-base-0.21.1-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/kcrcigylc73plzahdi3nkbq4angs853x-crypto-pubkey-types-0.4.3' from 'https://cache.nixos.org'...
copying path '/nix/store/81acvq5zliil9dd9c9h006w8snxqya5k-haskell-gi-overloading-1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/hhj80ngjb1pr1nw2wxxyhxay9s6nw524-RSA-2.3.0-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/8wi4av7vvksddl4l68rmxrna3abzwnbf-crypto-api-0.13.3' from 'https://cache.nixos.org'...
copying path '/nix/store/h75gnbnb5a7w9v1nv3di57n7x86hs4m0-haskell-lexer-1.0.1-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/p0cs5r4srpnvl0mhkslv4m0zhpm3fdbz-gi-gtk-declarative-0.1.0-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/zzw0jmsl9y9ra6mw8lp5zz91wvlaalky-authenticate-oauth-1.6-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/z8z81zpydvvjbk8pfwyaj58h8lg7csa4-haskell-gi-base-0.21.1' from 'https://cache.nixos.org'...
copying path '/nix/store/kf9l6krhjfbq72qpb0rjpjqa32ggbrrc-haskell-lexer-1.0.1' from 'https://cache.nixos.org'...
copying path '/nix/store/haiyqfk7x0ac4j19am317h5xw6335r0a-mmorph-1.1.2-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/ycd5v40ybak5b2vl5qpb58csm81rrkmj-pretty-show-1.7-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/p42g0sbdzbj1v08fpbbyb4wzdms4ln5z-RSA-2.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/zz1v3vbdyw7jbchpldd11f7igycj9pqx-mmorph-1.1.2' from 'https://cache.nixos.org'...
copying path '/nix/store/aa148lwnm6ppiy27k7a133fwlphj93id-pipes-4.3.9-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/qyvissiliwmp898f8z63dxh17s3l8j1m-pretty-show-1.7' from 'https://cache.nixos.org'...
copying path '/nix/store/r0w21ddqr18cp1m84w30jm41xvyvlywh-regex-tdfa-1.2.3.1-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/rzawymr61r7v91hwy2xdsg406qhrprzk-gi-gtk-declarative-app-simple-0.1.0-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/ml5skdqp9qz1208msiyvjp77l5ks1l45-pipes-4.3.9' from 'https://cache.nixos.org'...
copying path '/nix/store/i77ck41jr4b86jsavrldzyh124br95gs-pipes-concurrency-2.0.11-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/qqj71wcfxb58nrrns2k21l24w24i715d-authenticate-oauth-1.6' from 'https://cache.nixos.org'...
copying path '/nix/store/frrxxlkxmg0yhgabrqcmlv6x9cmv1b10-regex-tdfa-1.2.3.1' from 'https://cache.nixos.org'...
copying path '/nix/store/x2xgjwy4ad2q6mic0zwzyi98ibpf02x1-pipes-concurrency-2.0.11' from 'https://cache.nixos.org'...
copying path '/nix/store/lk77zg27gl3bfcd24ssn28fllld7pi6d-req-1.1.0-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/rz0562w0mk2qy628jp5gija2c9hp3irn-xdg-basedir-0.2.2-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/mfg915nin5k25dmzld67csr1xpwyyp2c-xml-types-0.3.6-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/zxmvdbf06jmr12abkihf4j55wx4j2s2g-req-1.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/0jdrni7gmj9cwivybjvlfq9w9h9iv4b0-xml-conduit-1.8.0-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/xywlf842zcdav8hibn24pkk6lbfmqsy0-xml-types-0.3.6' from 'https://cache.nixos.org'...
copying path '/nix/store/ihhrw82d4pgyzs3griq5l3srlr2b0k7a-xdg-basedir-0.2.2' from 'https://cache.nixos.org'...
copying path '/nix/store/dvmlqbhb7hdb0w4fz8zszzzmcgad6zpr-haskell-gi-0.21.4-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/1w7nivvrd52cngyqaknvzdswn99raxk6-xml-conduit-1.8.0' from 'https://cache.nixos.org'...
copying path '/nix/store/mwmps0fp28nd4q5jpizc1a44q6xxkck0-haskell-gi-0.21.4' from 'https://cache.nixos.org'...
copying path '/nix/store/6q9ylml1ak9k3k847zvlmwrhx59xk0hg-gi-glib-2.0.17' from 'https://cache.nixos.org'...
copying path '/nix/store/sfc24mw30slz81jmzn5r3xgpxyi153qf-gi-cairo-1.0.17' from 'https://cache.nixos.org'...
copying path '/nix/store/xxsyfwcaqkxc08z2b4vbyrv2n2hmvwj3-gi-gobject-2.0.16' from 'https://cache.nixos.org'...
copying path '/nix/store/jyps9mph07i82m2xkibk5fsi9r37dqxn-gi-gio-2.0.18' from 'https://cache.nixos.org'...
copying path '/nix/store/rszqpxm0ypb5yfcsbcm93zkin1sykhdr-gi-atk-2.0.15' from 'https://cache.nixos.org'...
copying path '/nix/store/wb2vrb9aak8975cm5sar971fljyxx6xa-gi-pango-1.0.16' from 'https://cache.nixos.org'...
copying path '/nix/store/dly7cpk6z3a4khbwp0la6fbm78bs85la-gi-gdkpixbuf-2.0.16' from 'https://cache.nixos.org'...
copying path '/nix/store/lfd4anlks1m9pwc3361455cfh1nnrr7s-gi-gdk-3.0.16' from 'https://cache.nixos.org'...
copying path '/nix/store/gm1ggslr73bf7fn8fa0mnyrvcs5zd1za-gi-gtk-3.0.24' from 'https://cache.nixos.org'...
copying path '/nix/store/6hkwxjcrglkmqx1yvh80bi5gnxwk1s3d-gi-gtk-declarative-0.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/91a4dz8ggn1sh56wksllnk4hlkrgq2wh-gi-gtk-declarative-app-simple-0.1.0' from 'https://cache.nixos.org'...
building '/nix/store/ah8fhx3c8jgv994vgs9x458l67nnz814-lambda-launcher-0.1.0.0.drv'...
setupCompilerEnvironmentPhase
Build with /nix/store/r12lm8my92akriijjaiivghindbizzp2-ghc-8.4.4.
unpacking sources
unpacking source archive /nix/store/3sw7a6y35q7wmrrkj7xiyqg7xrv4wiwk-lambda-launcher
source root is lambda-launcher
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/build/setup-package.conf.d -j1 -threaded
[1 of 1] Compiling Main             ( /nix/store/4mdp8nhyfddh7bllbi7xszz7k9955n79-Setup.hs, /build/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/pf9wcira9abq454hcwrbqkdgyqmj367q-lambda-launcher-0.1.0.0 --libdir=$prefix/lib/$compiler --libsubdir=$abi/$libname --docdir=/nix/store/bb91s48p0hp5b43fgl3kpp8qhq2nipa4-lambda-launcher-0.1.0.0-doc/share/doc/lambda-launcher-0.1.0.0 --with-gcc=gcc --package-db=/build/package.conf.d --ghc-option=-j1 --disable-split-objs --enable-library-profiling --profiling-detail=exported-functions --disable-profiling --enable-shared --disable-coverage --enable-static --disable-executable-dynamic --enable-tests --enable-library-vanilla --enable-library-for-ghci --ghc-option=-split-sections --extra-lib-dirs=/nix/store/zayl6yjayksyha5ndhxm6lmhr51i8sj6-ncurses-6.1-20190112/lib --extra-lib-dirs=/nix/store/cxiayilwj3ccnswhqmw00bhnnd0zfrcb-gmp-6.1.2/lib --extra-include-dirs=/nix/store/i4ddykjf873vsg4f6l17gxjklnghbnqn-gobject-introspection-1.56.0-dev/include --extra-lib-dirs=/nix/store/i4ddykjf873vsg4f6l17gxjklnghbnqn-gobject-introspection-1.56.0-dev/lib --extra-include-dirs=/nix/store/bjqrigphx5wyp00xb8r56yl9cnm5nqll-libffi-3.2.1-dev/include --extra-lib-dirs=/nix/store/bjqrigphx5wyp00xb8r56yl9cnm5nqll-libffi-3.2.1-dev/lib --extra-lib-dirs=/nix/store/k03gfmngr1gcir94m5xzqrg9ignb77nd-libffi-3.2.1/lib --extra-include-dirs=/nix/store/gliiw2pyz6i1rg8kxa2qq0sbl3lf5pk7-glib-2.56.0-dev/include --extra-lib-dirs=/nix/store/gliiw2pyz6i1rg8kxa2qq0sbl3lf5pk7-glib-2.56.0-dev/lib --extra-include-dirs=/nix/store/8bk02ngzpcgr0k35jmlyhpfpfjb7bzgr-zlib-1.2.11-dev/include --extra-lib-dirs=/nix/store/8bk02ngzpcgr0k35jmlyhpfpfjb7bzgr-zlib-1.2.11-dev/lib --extra-lib-dirs=/nix/store/3s920c43pgzi6vdabjs90in308jnbckv-zlib-1.2.11/lib --extra-include-dirs=/nix/store/9igls2z8mzyvwr8bb3rqxyqa7d6d2fdg-gettext-0.19.8.1/include --extra-lib-dirs=/nix/store/9igls2z8mzyvwr8bb3rqxyqa7d6d2fdg-gettext-0.19.8.1/lib --extra-include-dirs=/nix/store/z4s5k6hayk1xb3v6qn0nb92jsp4qad1s-glibc-iconv-2.27/include --extra-lib-dirs=/nix/store/363g8wdpaj537x7bb3n1dxqq50d8s6ga-glib-2.56.0/lib --extra-lib-dirs=/nix/store/8nqchqk71xv9b6rswkasc6bflqml95fv-gobject-introspection-1.56.0/lib
Using Parsec parser
Configuring lambda-launcher-0.1.0.0...
Dependency aeson ==1.*: using aeson-1.3.1.1
Dependency async ==2.*: using async-2.2.1
Dependency base ==4.*: using base-4.11.1.0
Dependency bytestring ==0.10.*: using bytestring-0.10.8.2
Dependency data-default-class ==0.*: using data-default-class-0.1.2.0
Dependency directory ==1.*: using directory-1.3.1.5
Dependency filepath ==1.*: using filepath-1.4.2
Dependency gi-gdk ==3.*: using gi-gdk-3.0.16
Dependency gi-glib ==2.*: using gi-glib-2.0.17
Dependency gi-gobject ==2.*: using gi-gobject-2.0.16
Dependency gi-gtk ==3.*: using gi-gtk-3.0.24
Dependency gi-gtk-declarative ==0.*: using gi-gtk-declarative-0.1.0
Dependency gi-gtk-declarative-app-simple ==0.*: using
gi-gtk-declarative-app-simple-0.1.0
Dependency haskell-gi ==0.*: using haskell-gi-0.21.4
Dependency haskell-gi-base ==0.*: using haskell-gi-base-0.21.1
Dependency process ==1.*: using process-1.6.3.0
Dependency req ==1.*: using req-1.1.0
Dependency text ==1.*: using text-1.2.3.1
Dependency vector ==0.*: using vector-0.12.0.1
Source component graph: component exe:lambda-launcher
Configured component graph:
    component lambda-launcher-0.1.0.0-HA7P56BbctkEJlspUTZol7-lambda-launcher
        include base-4.11.1.0
        include process-1.6.3.0
        include directory-1.3.1.5
        include async-2.2.1-1CuEIvGS3OJLsN4gbNyjc9
        include bytestring-0.10.8.2
        include gi-gobject-2.0.16-LFRWcSxt2vv9u3PJt2IUpB
        include gi-glib-2.0.17-LDd9vMGLab92lfVYOCxwHF
        include gi-gtk-3.0.24-8oOWLHquvrP90rlhYDqa8E
        include gi-gtk-declarative-0.1.0-LZb71if8ONaDBuw0UdJmlw
        include gi-gtk-declarative-app-simple-0.1.0-5eeK3FRf9gh6FZDL3tpCPc
        include gi-gdk-3.0.16-3jnEKbi3CS03YLHwMlOWzL
        include haskell-gi-0.21.4-5BIsHIIxMnz9Iwmms52OHq
        include haskell-gi-base-0.21.1-DNrno1CcQAxD3Vn0WiIXtr
        include text-1.2.3.1
        include vector-0.12.0.1-4awQG9XUvVEBfJgKGHBhOb
        include aeson-1.3.1.1-2HlXu9m4gDPKpJolKdWmih
        include filepath-1.4.2
        include req-1.1.0-PN8xXYtoZg8RBxZpKnKEK
        include data-default-class-0.1.2.0-2kYzERBLX3wJoPfj7mwVvW
Linked component graph:
    unit lambda-launcher-0.1.0.0-HA7P56BbctkEJlspUTZol7-lambda-launcher
        include base-4.11.1.0
        include process-1.6.3.0
        include directory-1.3.1.5
        include async-2.2.1-1CuEIvGS3OJLsN4gbNyjc9
        include bytestring-0.10.8.2
        include gi-gobject-2.0.16-LFRWcSxt2vv9u3PJt2IUpB
        include gi-glib-2.0.17-LDd9vMGLab92lfVYOCxwHF
        include gi-gtk-3.0.24-8oOWLHquvrP90rlhYDqa8E
        include gi-gtk-declarative-0.1.0-LZb71if8ONaDBuw0UdJmlw
        include gi-gtk-declarative-app-simple-0.1.0-5eeK3FRf9gh6FZDL3tpCPc
        include gi-gdk-3.0.16-3jnEKbi3CS03YLHwMlOWzL
        include haskell-gi-0.21.4-5BIsHIIxMnz9Iwmms52OHq
        include haskell-gi-base-0.21.1-DNrno1CcQAxD3Vn0WiIXtr
        include text-1.2.3.1
        include vector-0.12.0.1-4awQG9XUvVEBfJgKGHBhOb
        include aeson-1.3.1.1-2HlXu9m4gDPKpJolKdWmih
        include filepath-1.4.2
        include req-1.1.0-PN8xXYtoZg8RBxZpKnKEK
        include data-default-class-0.1.2.0-2kYzERBLX3wJoPfj7mwVvW
Ready component graph:
    definite lambda-launcher-0.1.0.0-HA7P56BbctkEJlspUTZol7-lambda-launcher
        depends base-4.11.1.0
        depends process-1.6.3.0
        depends directory-1.3.1.5
        depends async-2.2.1-1CuEIvGS3OJLsN4gbNyjc9
        depends bytestring-0.10.8.2
        depends gi-gobject-2.0.16-LFRWcSxt2vv9u3PJt2IUpB
        depends gi-glib-2.0.17-LDd9vMGLab92lfVYOCxwHF
        depends gi-gtk-3.0.24-8oOWLHquvrP90rlhYDqa8E
        depends gi-gtk-declarative-0.1.0-LZb71if8ONaDBuw0UdJmlw
        depends gi-gtk-declarative-app-simple-0.1.0-5eeK3FRf9gh6FZDL3tpCPc
        depends gi-gdk-3.0.16-3jnEKbi3CS03YLHwMlOWzL
        depends haskell-gi-0.21.4-5BIsHIIxMnz9Iwmms52OHq
        depends haskell-gi-base-0.21.1-DNrno1CcQAxD3Vn0WiIXtr
        depends text-1.2.3.1
        depends vector-0.12.0.1-4awQG9XUvVEBfJgKGHBhOb
        depends aeson-1.3.1.1-2HlXu9m4gDPKpJolKdWmih
        depends filepath-1.4.2
        depends req-1.1.0-PN8xXYtoZg8RBxZpKnKEK
        depends data-default-class-0.1.2.0-2kYzERBLX3wJoPfj7mwVvW
Using Cabal-2.2.0.1 compiled by ghc-8.4
Using compiler: ghc-8.4.4
Using install prefix:
/nix/store/pf9wcira9abq454hcwrbqkdgyqmj367q-lambda-launcher-0.1.0.0
Executables installed in:
/nix/store/pf9wcira9abq454hcwrbqkdgyqmj367q-lambda-launcher-0.1.0.0/bin
Libraries installed in:
/nix/store/pf9wcira9abq454hcwrbqkdgyqmj367q-lambda-launcher-0.1.0.0/lib/ghc-8.4.4/x86_64-linux-ghc-8.4.4/lambda-launcher-0.1.0.0
Dynamic Libraries installed in:
/nix/store/pf9wcira9abq454hcwrbqkdgyqmj367q-lambda-launcher-0.1.0.0/lib/ghc-8.4.4/x86_64-linux-ghc-8.4.4
Private executables installed in:
/nix/store/pf9wcira9abq454hcwrbqkdgyqmj367q-lambda-launcher-0.1.0.0/libexec/x86_64-linux-ghc-8.4.4/lambda-launcher-0.1.0.0
Data files installed in:
/nix/store/pf9wcira9abq454hcwrbqkdgyqmj367q-lambda-launcher-0.1.0.0/share/x86_64-linux-ghc-8.4.4/lambda-launcher-0.1.0.0
Documentation installed in:
/nix/store/bb91s48p0hp5b43fgl3kpp8qhq2nipa4-lambda-launcher-0.1.0.0-doc/share/doc/lambda-launcher-0.1.0.0
Configuration files installed in:
/nix/store/pf9wcira9abq454hcwrbqkdgyqmj367q-lambda-launcher-0.1.0.0/etc
No alex found
Using ar found on system at:
/nix/store/5vyv136pqs75pj0b8vcpdyc03dmn9p0n-binutils-2.30/bin/ar
No c2hs found
No cpphs found
No doctest found
Using gcc version 7.3.0 given by user at:
/nix/store/cy3x06bfplivhrvx6rf7vkszx81c09nn-gcc-wrapper-7.3.0/bin/gcc
Using ghc version 8.4.4 found on system at:
/nix/store/r12lm8my92akriijjaiivghindbizzp2-ghc-8.4.4/bin/ghc
Using ghc-pkg version 8.4.4 found on system at:
/nix/store/r12lm8my92akriijjaiivghindbizzp2-ghc-8.4.4/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.20.0 found on system at:
/nix/store/r12lm8my92akriijjaiivghindbizzp2-ghc-8.4.4/bin/haddock
No happy found
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at:
/nix/store/r12lm8my92akriijjaiivghindbizzp2-ghc-8.4.4/bin/hpc
Using hsc2hs version 0.68.3 found on system at:
/nix/store/r12lm8my92akriijjaiivghindbizzp2-ghc-8.4.4/bin/hsc2hs
No hscolour found
No jhc found
Using ld found on system at:
/nix/store/5c5vbvcybxllw3jdwzm1s0gx7j1464rc-binutils-wrapper-2.30/bin/ld
No lhc found
No lhc-pkg found
No pkg-config found
Using runghc version 8.4.4 found on system at:
/nix/store/r12lm8my92akriijjaiivghindbizzp2-ghc-8.4.4/bin/runghc
Using strip version 2.30 found on system at:
/nix/store/5vyv136pqs75pj0b8vcpdyc03dmn9p0n-binutils-2.30/bin/strip
Using tar found on system at:
/nix/store/n9w6xkk15nkpslvzhwrpi90pv3kkdal6-gnutar-1.30/bin/tar
No uhc found
building
Preprocessing executable 'lambda-launcher' for lambda-launcher-0.1.0.0..
Building executable 'lambda-launcher' for lambda-launcher-0.1.0.0..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: LambdaLauncher.Plugins.Kill
[ 1 of 16] Compiling LambdaLauncher.Types ( src/LambdaLauncher/Types.hs, dist/build/lambda-launcher/lambda-launcher-tmp/LambdaLauncher/Types.o )
[ 2 of 16] Compiling LambdaLauncher.Plugins.Wmctrl ( src/LambdaLauncher/Plugins/Wmctrl.hs, dist/build/lambda-launcher/lambda-launcher-tmp/LambdaLauncher/Plugins/Wmctrl.o )
[ 3 of 16] Compiling LambdaLauncher.Plugins.Sway ( src/LambdaLauncher/Plugins/Sway.hs, dist/build/lambda-launcher/lambda-launcher-tmp/LambdaLauncher/Plugins/Sway.o )
[ 4 of 16] Compiling LambdaLauncher.Plugins.Support ( src/LambdaLauncher/Plugins/Support.hs, dist/build/lambda-launcher/lambda-launcher-tmp/LambdaLauncher/Plugins/Support.o )
[ 5 of 16] Compiling LambdaLauncher.Plugins.Wiki ( src/LambdaLauncher/Plugins/Wiki.hs, dist/build/lambda-launcher/lambda-launcher-tmp/LambdaLauncher/Plugins/Wiki.o )
[ 6 of 16] Compiling LambdaLauncher.Plugins.Stackoverflow ( src/LambdaLauncher/Plugins/Stackoverflow.hs, dist/build/lambda-launcher/lambda-launcher-tmp/LambdaLauncher/Plugins/Stackoverflow.o )
[ 7 of 16] Compiling LambdaLauncher.Plugins.Qalc ( src/LambdaLauncher/Plugins/Qalc.hs, dist/build/lambda-launcher/lambda-launcher-tmp/LambdaLauncher/Plugins/Qalc.o )
[ 8 of 16] Compiling LambdaLauncher.Plugins.Kill ( src/LambdaLauncher/Plugins/Kill.hs, dist/build/lambda-launcher/lambda-launcher-tmp/LambdaLauncher/Plugins/Kill.o )
[ 9 of 16] Compiling LambdaLauncher.Plugins.Google ( src/LambdaLauncher/Plugins/Google.hs, dist/build/lambda-launcher/lambda-launcher-tmp/LambdaLauncher/Plugins/Google.o )
[10 of 16] Compiling LambdaLauncher.Plugins.Files ( src/LambdaLauncher/Plugins/Files.hs, dist/build/lambda-launcher/lambda-launcher-tmp/LambdaLauncher/Plugins/Files.o )
[11 of 16] Compiling LambdaLauncher.Plugins.Emacs ( src/LambdaLauncher/Plugins/Emacs.hs, dist/build/lambda-launcher/lambda-launcher-tmp/LambdaLauncher/Plugins/Emacs.o )
[12 of 16] Compiling LambdaLauncher.Plugins.Duckduckgo ( src/LambdaLauncher/Plugins/Duckduckgo.hs, dist/build/lambda-launcher/lambda-launcher-tmp/LambdaLauncher/Plugins/Duckduckgo.o )
[13 of 16] Compiling LambdaLauncher.Plugins.Command ( src/LambdaLauncher/Plugins/Command.hs, dist/build/lambda-launcher/lambda-launcher-tmp/LambdaLauncher/Plugins/Command.o )
[14 of 16] Compiling LambdaLauncher.Plugins ( src/LambdaLauncher/Plugins.hs, dist/build/lambda-launcher/lambda-launcher-tmp/LambdaLauncher/Plugins.o )
[15 of 16] Compiling LambdaLauncher.Main ( src/LambdaLauncher/Main.hs, dist/build/lambda-launcher/lambda-launcher-tmp/LambdaLauncher/Main.o )

src/LambdaLauncher/Main.hs:66:42: error:
    Not in scope: type constructor or class ‘AppView’
   |
66 | searchView :: Configuration ->  State -> AppView Window Event
   |                                          ^^^^^^^
builder for '/nix/store/ah8fhx3c8jgv994vgs9x458l67nnz814-lambda-launcher-0.1.0.0.drv' failed with exit code 1
error: build of '/nix/store/ah8fhx3c8jgv994vgs9x458l67nnz814-lambda-launcher-0.1.0.0.drv' failed
```

**Comment by balsoft** [comment]
Whoops. I'll fix this this evening. In the meantime, you can try `NIX_PATH=nixpkgs=https://github.org/nixos/nixpkgs-channels/tarball/nixos-unstable nix build`

**Comment by balsoft** [comment]
Sorry, I can't figure out a good way to make this build on 18.09, I will have to pin a nixpkgs version to a confirmed-working one. Thanks for the feedback!

**Comment by balsoft** [comment]
@ebzzry This should work now. The nixpkgs version is pinned.

**Comment by ebzzry** [comment]
Is that a valid GitHub account?

**Comment by ebzzry** [comment]
Thanks, it builds fine now!
